# Data Wrangling for 2 months and getting the % availability of each carpark

In [ ]:
import csv
import ast
import numpy
import datetime
import requests as req

new=[]
f = open('september.csv') #whatever the file is 
csv_f = csv.reader(f)
for row in csv_f:
    new.append(row) #append each line of csv as list 
    

coord_data={}


data = req.get("https://data.gov.sg/api/action/datastore_search?resource_id=139a3035-e624-4f56-b63f-89ae28d4ae4c&limit=5000" ).json()
for i in range(len(data['result']['records'])):
    coord_data[data['result']['records'][i]['car_park_no']]=[(data['result']['records'][i]['x_coord']),(data['result']['records'][i]['y_coord'])]
    

    
for i in range(len(new)):
    new[i][1]=(ast.literal_eval(new[i][1])) #convert to dictionary from csv
    if new[i][1]['carpark_number'] in coord_data:
        new[i][1]['x_coord']=coord_data[new[i][1]['carpark_number']][0]
        new[i][1]['y_coord']=coord_data[new[i][1]['carpark_number']][1]
    else:
        new[i][1]['x_coord']= float("nan")
        new[i][1]['y_coord']= float("nan")
    
        
    if len(new[i][1]['carpark_info'])==1:
        new[i][1]['carpark_info']=(int(new[i][1]['carpark_info'][0]['lots_available'])/numpy.float64(new[i][1]['carpark_info'][0]['total_lots']))*100 #to prevent division by 0
    else:
        
        x=new[i][1]['carpark_info'] 
        available=0
        total=0
        for j in range(len(x)): #based on number of types of carpar
            available+=int(x[j]['lots_available'])
            total+=numpy.float64(x[j]['total_lots'])
        new[i][1]['carpark_info']=(available/total)*100 #convert to percentage

# for i in range(len(new)):
#     if len(new[i][1])<=3:
#         new.remove(new[i])

carpk=[]
date=[]
avail=[]
coordx=[]
coordy=[]

import pandas as pd
df = pd.DataFrame()
for i in range(len(new)):
    date.append(new[i][0])
    carpk.append(new[i][1]['carpark_number'])
    avail.append(new[i][1]['carpark_info'])
    coordx.append(new[i][1]['x_coord'])
    coordy.append(new[i][1]['y_coord'])


df['Date']=date
df['Carpark_Number']=carpk
df['Carpark_availability']=avail
df['Coord_x']=coordx
df['Coord_y']=coordy
df=df.dropna()
df.to_csv('Qn3_data.csv',index=False)

# To now create a machine language model based of the wrangled data

In [1]:
# open Q3_data.csv
import pandas as pd
# read the csv file
df = pd.read_csv('/Users/rachpradhan/Downloads/Question 2 Submission/Qn3_data (4).csv')
df

#train machine model based on Carpark_Number and Date to give the Carpark_Availability
#use the data from Q3_data.csv

import pandas as pd
import numpy as np
from sklearn import linear_model
from sklearn.model_selection import train_test_split
from sklearn.metrics import mean_squared_error, r2_score
import matplotlib.pyplot as plt

# read the csv file
df = pd.read_csv('/Users/rachpradhan/Downloads/Question 2 Submission/Qn3_data (4).csv')
df

# create a new dataframe with only the columns we need
df2 = df[['Carpark_Number', 'Date', 'Carpark_availability']]
df2

# give a number for each carpark in carpark_number
# to make training easier
carparkNumberList = []
for carparkNumber in df2['Carpark_Number']:
    carparkNumberList.append(carparkNumber)
# print(carparkNumberList)

# create a list of unique carpark numbers
uniqueCarparkNumberList = []
for carparkNumber in df2['Carpark_Number'].unique():
    uniqueCarparkNumberList.append(carparkNumber)
# print(uniqueCarparkNumberList)


# # create a dictionary of carpark numbers and their corresponding numbers
# carparkNumberDict = {}
# for idx,carparkNumber in enumerate(uniqueCarparkNumberList):
#     carparkNumberDict[carparkNumber] = idx
# # print(carparkNumberDict)

# # replace the carpark numbers with their corresponding numbers
# for idx,carparkNumber in enumerate(carparkNumberList):
#     carparkNumberList[idx] = carparkNumberDict[carparkNumber]


# for uniqueCarparks in uniqueCarparkNumberList:
#     # print(uniqueCarparks)
#     for idx,carparkNumber in enumerate(carparkNumberList):
#         if carparkNumber == uniqueCarparks:
#             carparkNumberList[idx] = uniqueCarparkNumberList.index(uniqueCarparks)
# print(carparkNumberList)

# for every unique carpark_number, give it a number


# split the data into training and testing
# train, test = train_test_split(df2, test_size=0.2)

# # create a unsupervised learning model
# x_train = train[['Carpark_Number', 'Date']]
# y_train = train['Carpark_availability']
# x_test = test[['Carpark_Number', 'Date']]
# y_test = test['Carpark_availability']

# # create a random forest model
# from sklearn.ensemble import RandomForestRegressor
# rf = RandomForestRegressor(n_estimators = 1000, random_state = 42)
# rf.fit(x_train, y_train)

# # make predictions
# predictions = rf.predict(x_test)
# predictions

In [2]:
# Create a time list 
# convert the date into just hours and minutes and seconds and make it into a list

# create a list of dates
dateList = []
for date in df2['Date']:
    dateList.append(date)
# print(dateList)

# create a list of hours
hourList = []
for date in dateList:
    hourList.append(date[11:13])
# print(hourList)

# create a list of minutes
minuteList = []
for date in dateList:
    minuteList.append(date[14:16])

# create a list of seconds
secondList = []
for date in dateList:
    secondList.append(date[17:19])

# create a list of time
timeList = []
for idx,hour in enumerate(hourList):
    timeList.append(hourList[idx] + minuteList[idx] + secondList[idx])
# print(timeList)

# print(timeList)
#113343
#001231

In [3]:
# add the carpark_number list as a column in the dataframe
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import os


# open Qn3_data (4).csv and read it into a dataframe

df = pd.read_csv('/Users/rachpradhan/Downloads/Question 2 Submission/Qn3_data (4).csv')
df

# take out Carpark_Number in another list

carpark_number = df['Carpark_Number'].tolist()
carpark_number

# find out all the unique carpark number

unique_carpark_number = set(carpark_number)
unique_carpark_number

# assign each item in carpark number to its index in unique carpark number

carpark_number_index = [list(unique_carpark_number).index(i) for i in carpark_number]
carpark_number_index
df3 = pd.read_csv('/Users/rachpradhan/Downloads/Question 2 Submission/Qn3_data (4).csv')
df3['CarparkValue'] = carpark_number_index
df3['timeValue'] = timeList
df3

,Date,Carpark_Number,Carpark_availability,Coord_x,Coord_y,CarparkValue,timeValue
0,2022-09-01T01:00:27+08:00,HE12,50.476190,26367.5806,30069.2434,732,010027
1,2022-09-01T01:00:27+08:00,HLM,82.504288,29354.6692,29687.5080,104,010027
2,2022-09-01T01:00:27+08:00,RHM,37.082067,26359.4531,29876.1692,455,010027
3,2022-09-01T01:00:27+08:00,BM29,83.505155,26194.9184,29563.3295,960,010027
4,2022-09-01T01:00:27+08:00,Q81,82.291667,23531.2041,32206.3235,1503,010027
...,...,...,...,...,...,...,...
1327327,2022-09-30T01:00:27+08:00,B65M,48.600884,40577.3467,33351.3208,921,010027
1327328,2022-09-30T01:00:27+08:00,B65L,0.000000,40720.5785,33389.4366,1359,010027
1327329,2022-09-30T01:00:27+08:00,BE3,19.281046,28121.0801,38268.7852,1297,010027
1327330,2022-09-30T01:00:27+08:00,BE3R,41.538462,28240.0745,38359.6695,879,010027
1327331,2022-09-30T01:00:27+08:00,B8B,46.987952,38531.1666,34114.4997,1551,010027

In [4]:
df4 = df3[['CarparkValue', 'timeValue', 'Carpark_availability']]
df4

         CarparkValue timeValue  Carpark_availability
0                 732    010027             50.476190
1                 104    010027             82.504288
2                 455    010027             37.082067
3                 960    010027             83.505155
4                1503    010027             82.291667
...               ...       ...                   ...
1327327           921    010027             48.600884
1327328          1359    010027              0.000000
1327329          1297    010027             19.281046
1327330           879    010027             41.538462
1327331          1551    010027             46.987952

[1327332 rows x 3 columns]

# Running the random Forest model

In [5]:
# we only need CarparkValue, Date and Carpark_availability
# using the carparkValue and Date predict the Carpark_availability


# split the data into training and testing
train, test = train_test_split(df4, test_size=0.2)

# create a unsupervised learning model
x_train = train[['CarparkValue', 'timeValue']]
y_train = train['Carpark_availability']
x_test = test[['CarparkValue', 'timeValue']]
y_test = test['Carpark_availability']

# create a random forest model
from sklearn.ensemble import RandomForestRegressor
rf = RandomForestRegressor(n_estimators = 1000, random_state = 42)
rf.fit(x_train, y_train)

# make predictions
predictions = rf.predict(x_test)
predictions

# # The coefficients
# print('Coefficients: \n', regr.coef_)
# # The mean squared error
# print('Mean squared error: %.2f'
#       % mean_squared_error(y_test, y_pred))
# # The coefficient of determination: 1 is perfect prediction
# print('Coefficient of determination: %.2f'
#       % r2_score(y_test, y_pred))

# # Plot outputs
# plt.scatter(x_test, y_test,  color='black')
# plt.plot(x_test, y_pred, color='blue', linewidth=3)

# plt.xticks(())
# plt.yticks(())
# plt.show()

In [ ]:
# test the model
print(rf.score(x_test, y_test))

# print rmse
from sklearn.metrics import mean_squared_error
from math import sqrt

rms = sqrt(mean_squared_error(y_test, predictions))
print(rms)

In [ ]:
# saving the random forest to a pickle file
# save the model to a pickle file
import pickle
pickle.dump(rf, open('model.pkl','wb'))

# check prediction
model = pickle.load(open('model.pkl','rb'))

# Converting the coords to lat and long

In [ ]:
df4.to_csv('location_data.csv', index=False)

#get the 5 nearest carparks based on latitude and longitude from df4
from math import sin, cos, sqrt, atan2,radians

#Distance function between two lat/lon
def getDist(lat1,lon1,lat2,lon2):
  R = 6373.0

  lat1 = radians(lat1)
  lon1 = radians(lon1)
  lat2 = radians(lat2)
  lon2 = radians(lon2)

  dlon = lon2 - lon1
  dlat = lat2 - lat1

  a = sin(dlat / 2)**2 + cos(lat1) * cos(lat2) * sin(dlon / 2)**2
  c = 2 * atan2(sqrt(a), sqrt(1 - a))

  return R * c

#Apply distance function to dataframe
df4['dist']=list(map(lambda k: getDist(df4.loc[k]['latitude'],df4.loc[k]['longitude'],1.288210,103.946332), df4.index))

#This will give all locations within radius of 4 km arrange by distance
df4[df4['dist']<4].sort_values(by='dist')[0:5]

#sorting by distance to be used later in the app!